#    SERVER         /  SERVICE         /  rpc METHOD
GRPC localhost:9001/BillingService/CreateBillingAccount

{

  "patientId" : "11",
  "name" : "Ankush Desai",
  "email": "ankush.desai@example.com"
}